### ISSUE TITLE
Add universal button

### ISSUE THREAD

**Issue by FireSquid6** [matchmake-ink/matchmake.ink#37]
The button should:
- have prop for `onPress` callback
- have prop for `label` string
- have prop for `class-override` string

**Comment by aishwarya-mali** [comment]
@FireSquid6 I'd like to work on this issue. I have sent you request on discord as well.

**Comment by FireSquid6** [comment]
> @FireSquid6 I'd like to work on this issue. I have sent you request on discord as well.

Go for it!
